// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: kconf_servlet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionedConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version int64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Value   *anypb.Any `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VersionedConfig) Reset() {
	*x = VersionedConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kconf_servlet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedConfig) ProtoMessage() {}

func (x *VersionedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kconf_servlet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedConfig.ProtoReflect.Descriptor instead.
func (*VersionedConfig) Descriptor() ([]byte, []int) {
	return file_kconf_servlet_proto_rawDescGZIP(), []int{0}
}

func (x *VersionedConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VersionedConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionedConfig) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetVersionedConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetVersionedConfigRequest) Reset() {
	*x = GetVersionedConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kconf_servlet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionedConfigRequest) ProtoMessage() {}

func (x *GetVersionedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconf_servlet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionedConfigRequest.ProtoReflect.Descriptor instead.
func (*GetVersionedConfigRequest) Descriptor() ([]byte, []int) {
	return file_kconf_servlet_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionedConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WatchVersionedConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*ConfigQuery `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *WatchVersionedConfigRequest) Reset() {
	*x = WatchVersionedConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kconf_servlet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchVersionedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVersionedConfigRequest) ProtoMessage() {}

func (x *WatchVersionedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconf_servlet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVersionedConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchVersionedConfigRequest) Descriptor() ([]byte, []int) {
	return file_kconf_servlet_proto_rawDescGZIP(), []int{2}
}

func (x *WatchVersionedConfigRequest) GetQueries() []*ConfigQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type WatchVersionedConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*VersionedConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *WatchVersionedConfigResponse) Reset() {
	*x = WatchVersionedConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kconf_servlet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchVersionedConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVersionedConfigResponse) ProtoMessage() {}

func (x *WatchVersionedConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconf_servlet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVersionedConfigResponse.ProtoReflect.Descriptor instead.
func (*WatchVersionedConfigResponse) Descriptor() ([]byte, []int) {
	return file_kconf_servlet_proto_rawDescGZIP(), []int{3}
}

func (x *WatchVersionedConfigResponse) GetConfigs() []*VersionedConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ConfigQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ConfigQuery) Reset() {
	*x = ConfigQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kconf_servlet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQuery) ProtoMessage() {}

func (x *ConfigQuery) ProtoReflect() protoreflect.Message {
	mi := &file_kconf_servlet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQuery.ProtoReflect.Descriptor instead.
func (*ConfigQuery) Descriptor() ([]byte, []int) {
	return file_kconf_servlet_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigQuery) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_kconf_servlet_proto protoreflect.FileDescriptor

var file_kconf_servlet_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x6c, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x2f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x58, 0x0a, 0x1b, 0x57, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x39, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x1c,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x32, 0xf7,
	0x01, 0x0a, 0x0c, 0x4b, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x65, 0x72, 0x76, 0x6c, 0x65, 0x74, 0x12,
	0x68, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x2e, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x7d, 0x0a, 0x14, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x2f, 0x2e, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x30, 0x2e, 0x71, 0x65, 0x63, 0x6f, 0x2e, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x71, 0x65, 0x63, 0x6f,
	0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6b, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kconf_servlet_proto_rawDescOnce sync.Once
	file_kconf_servlet_proto_rawDescData = file_kconf_servlet_proto_rawDesc
)

func file_kconf_servlet_proto_rawDescGZIP() []byte {
	file_kconf_servlet_proto_rawDescOnce.Do(func() {
		file_kconf_servlet_proto_rawDescData = protoimpl.X.CompressGZIP(file_kconf_servlet_proto_rawDescData)
	})
	return file_kconf_servlet_proto_rawDescData
}

var file_kconf_servlet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kconf_servlet_proto_goTypes = []interface{}{
	(*VersionedConfig)(nil),              // 0: qeco.kconf.apis.v1.VersionedConfig
	(*GetVersionedConfigRequest)(nil),    // 1: qeco.kconf.apis.v1.GetVersionedConfigRequest
	(*WatchVersionedConfigRequest)(nil),  // 2: qeco.kconf.apis.v1.WatchVersionedConfigRequest
	(*WatchVersionedConfigResponse)(nil), // 3: qeco.kconf.apis.v1.WatchVersionedConfigResponse
	(*ConfigQuery)(nil),                  // 4: qeco.kconf.apis.v1.ConfigQuery
	(*anypb.Any)(nil),                    // 5: google.protobuf.Any
}
var file_kconf_servlet_proto_depIdxs = []int32{
	5, // 0: qeco.kconf.apis.v1.VersionedConfig.value:type_name -> google.protobuf.Any
	4, // 1: qeco.kconf.apis.v1.WatchVersionedConfigRequest.queries:type_name -> qeco.kconf.apis.v1.ConfigQuery
	0, // 2: qeco.kconf.apis.v1.WatchVersionedConfigResponse.configs:type_name -> qeco.kconf.apis.v1.VersionedConfig
	1, // 3: qeco.kconf.apis.v1.KConfServlet.GetVersionedConfig:input_type -> qeco.kconf.apis.v1.GetVersionedConfigRequest
	2, // 4: qeco.kconf.apis.v1.KConfServlet.WatchVersionedConfig:input_type -> qeco.kconf.apis.v1.WatchVersionedConfigRequest
	0, // 5: qeco.kconf.apis.v1.KConfServlet.GetVersionedConfig:output_type -> qeco.kconf.apis.v1.VersionedConfig
	3, // 6: qeco.kconf.apis.v1.KConfServlet.WatchVersionedConfig:output_type -> qeco.kconf.apis.v1.WatchVersionedConfigResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kconf_servlet_proto_init() }
func file_kconf_servlet_proto_init() {
	if File_kconf_servlet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kconf_servlet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionedConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kconf_servlet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionedConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kconf_servlet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchVersionedConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kconf_servlet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchVersionedConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kconf_servlet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kconf_servlet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kconf_servlet_proto_goTypes,
		DependencyIndexes: file_kconf_servlet_proto_depIdxs,
		MessageInfos:      file_kconf_servlet_proto_msgTypes,
	}.Build()
	File_kconf_servlet_proto = out.File
	file_kconf_servlet_proto_rawDesc = nil
	file_kconf_servlet_proto_goTypes = nil
	file_kconf_servlet_proto_depIdxs = nil
}
